_target_: model.BigModel
pretrained_backbone_name: "resnet50"
frozen: true
pretrained: true
reduced_dim: 64
head:
  _target_: model.MLP
  initial_out_features: 20
  sizes: [64, 400]
  layers: ["Normal"]
  head_type: Normal
  activation: 
    _target_: torch.nn.ReLU