_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
lr: 0.01
criterion_scale: 1e-5
reset_rbf_mask: False
plugins:
  - _target_: method.Sharpening
    K: 64
    alpha: 0.4
    gamma: 0.1