_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
lr: 0.000167011223364483
ema_scale: 0.95
beta: 0.1
use_dynamic_alpha: False
criterion_scale: 1.0
retaingraph: True
plugins:
  - _target_: method.interval_penalization_mlp.MLPIntervalPenalization
    var_scale: 4.196907463555686
    lambda_int_drift: 5.710612264296477
    lambda_feat: 778.5931549949635
    use_hypercube_dist_loss: True
    dil_mode: False
    regularize_classifier: True