defaults:
  - _self_
  - dataset: mnist
  - scenario: class_inc
  - model: mlp
  - method: composer_interval_penalization_mlp

exp:
  run_func:
    _target_: visualization.activation_visualization
  seed: 42
  log_dir: outputs/activation_logs
  batch_size: 512
  epochs: 5
  gen_cm: False
  log_per_batch: False
  detect_anomaly: False
  cleanup: True
  calc_bwt: False
  calc_fwt: False
  acc_table: False
  dil: False
  num_samples_per_task: 20

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}
