defaults:
  - _self_
  - dataset: mnist
  - scenario: class_inc
  - model: mlp
  - method: composer_mas

exp:
  run_func:
    _target_: experiment.experiment
  seed: 42
  log_dir: # set during runtime to automatically created dir
  batch_size: 32
  epochs: 1
  gen_cm: False
  log_per_batch: False
  detect_anomaly: False
  cleanup: True
  dil: False

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}